### ISSUE TITLE
Well that was a blind side

### ISSUE THREAD

**Issue by dragonfire1119** [Neurony/laravel-query-cache#12]
Since this package was discontinued is there an alternative?

**Comment by zbiller** [comment]
Hi @dragonfire1119 

Please take a look at [Varbox](https://varbox.io).

Even though Varbox is paid software it also offers a full admin experience and a bunch of tools (query cache is one of them) to help you develop faster products with Laravel.

I suggest you take a look at the [Documentation](https://varbox.io/docs/2.x) to see if Varbox can help you in delivering a streamlined admin experience to your customers.

Thanks!

**Comment by dragonfire1119** [comment]
@zbiller Hello thanks for the reply. Not sure if that would work for me since I build my own Admin Panel.
