### ISSUE TITLE
Syntax error on delete query

### ISSUE THREAD

**Issue by juanangel123** [Neurony/laravel-query-cache#3]
Trace:

```
TypeError : Return value of Neurony\QueryCache\Database\QueryCacheBuilder::delete() must be of the type integer or null, none returned
 C:\Webs\test\vendor\neurony\laravel-query-cache\src\Database\QueryCacheBuilder.php:117
 C:\Webs\test\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:889
 C:\Webs\test\tests\Unit\ExampleTest.php:17
````
Just created an empty laravel repository with testbench to replicate the error. Example test:

```php
<?php

namespace Tests\Unit;

use App\User;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        User::query()->delete();

        $this->assertTrue(true);
    }
}
```
Environment:
* OS: Windows
* PHP 7.2.15
* Laravel 5.8.9

The problem is in the file ```Neurony\QueryCache\Database\QueryCacheBuilder```.
In the ```delete()``` method it's saying the return type as ?int
I'm not very familiar with PHP 7 return types yet, so I don't know if there is any return type that is valid for this case.

**Comment by zbiller** [comment]
Hey @juanangel123 

Thanks for spotting this!

This is now fixed, just update to use the version **1.1.1** of this package.

Thanks! :)
