### ISSUE TITLE
Laravel 6.2 Support

### ISSUE THREAD

**Issue by ppalashturov** [Neurony/laravel-query-cache#7]
Hi,
I have a problem with install composer to Laravel 6.2.

> Your requirements could not be resolved to an installable set of packages.

Can you add support for Laravel 6.2 please?

**Comment by zbiller** [comment]
Hi @ppalashturov 

This should now be fixed.
Please try using version `2.1.0` of this package (`^2.1` in your composer.json).

Thanks!

**Comment by ppalashturov** [comment]
> Hi @ppalashturov
> 
> This should now be fixed.
> Please try using version `2.1.0` of this package (`^2.1` in your composer.json).
> 
> Thanks!

Thanks! :)
