### ISSUE TITLE
how do I set an interval to invalidate the cache

### ISSUE THREAD

**Issue by nivanmorgan** [Neurony/laravel-query-cache#8]
If I enable all queries to be cached how do I set an interval for that cache?

**Comment by zbiller** [comment]
Hi @nivanmorgan 

The package doesn't support setting an interval, you should do that at Redis level for example.

If you want to invalidate the cache, please read here: https://github.com/Neurony/laravel-query-cache#enable--disable-query-caching

Thanks!
